# Generated by Django 6.0.5 on 2026-06-02 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shell_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='users',
            new_name='user',
        ),
    ]
